# Define folders and their download URLs
folders:

# Upscale Models      
  - target: models/upscale_models
    source: huggingface
    urls:
      - https://huggingface.co/LS110824/upscale/resolve/main/4xLSDIR.pth

# Lotus Depth
  - target: models/vae/lotus_depth
    source: huggingface
    urls:
      - https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
  - target: models/diffusion_models/lotus_depth
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/lotus/resolve/main/lotus-depth-d-v1-1.safetensors    

# SDXL
  - target: models/checkpoints/sdxl
    source: huggingface
    urls:
      - https://huggingface.co/SG161222/RealVisXL_V5.0/resolve/main/RealVisXL_V5.0_fp32.safetensors
  - target: models/loras/sdxl
    source: civitai
    ids:
      - 1236430 # realism lora by stable yogi
      - 1364069 # log color lora -  cinematic film style, Cineon, cinematic film stocks, raw

# QWEN Image
  - target: models/vae/qwen
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors
  - target: models/text_encoders/qwen
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors
  - target: models/diffusion_models/qwen
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_fp8_e4m3fn.safetensors               
      - https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_2509_fp8_e4m3fn.safetensors
  - target: models/loras/qwen
    source: huggingface
    urls:
      - https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Lightning-4steps-V1.0.safetensors             
      - https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-2509/Qwen-Image-Edit-2509-Lightning-4steps-V1.0-bf16.safetensors
  - target: models/controlnet/qwen
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Qwen-Image-InstantX-ControlNets/resolve/main/split_files/controlnet/Qwen-Image-InstantX-ControlNet-Union.safetensors
  - target: models/loras/qwen
    source: civitai
    ids:
      - 2424051 # flat log color lora - flatcolor Desaturate the image and lower the contrast to create a flat, ungraded look similar to a camera's log profile. Preserve details in the highlights and shadows
      - 2337354 # cinematic lora - in elusarca style, a movie still, cinematic
      - 2416596 # skin detailer lora
      - 2181911 # boring reality lora

# WAN2.2 General
  - target: models/vae/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors
  - target: models/text_encoders/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors
  - target: models/clip_vision/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors
  - target: models/diffusion_models/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors
  - target: models/diffusion_models/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/diffusion_models/wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors
  - target: models/loras/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_high_noise.safetensors
  - target: models/loras/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Comfy-Org/Wan_2.2_ComfyUI_Repackaged/resolve/main/split_files/loras/wan2.2_i2v_lightx2v_4steps_lora_v1_low_noise.safetensors

# WAN2.2 Animate
  - target: models/diffusion_models/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors
  - target: models/loras/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors
  - target: models/loras/wan22
    source: huggingface
    urls:
      - https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
